/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionButton: typeof import('./src/components/ui/ActionButton.vue')['default']
    BasicLayout: typeof import('./src/components/BasicLayout.vue')['default']
    ChatContainer: typeof import('./src/components/chat/ChatContainer.vue')['default']
    ChatHeader: typeof import('./src/components/chat/ChatHeader.vue')['default']
    ChatInput: typeof import('./src/components/chat/ChatInput.vue')['default']
    ChatMessageList: typeof import('./src/components/chat/ChatMessageList.vue')['default']
    ChatPrompts: typeof import('./src/components/chat/ChatPrompts.vue')['default']
    ChatRequest: typeof import('./src/components/chat/ChatRequest.vue')['default']
    Editor: typeof import('./src/components/Editor.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    MessageBubble: typeof import('./src/components/chat/MessageBubble.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SimpleChatTest: typeof import('./src/components/chat/SimpleChatTest.vue')['default']
  }
}
